### ISSUE TITLE
Anyone Faucet not working

### ISSUE THREAD

**Issue by glaucoab** [anyone-protocol/ator-relay-dashboard#114]
**Description**
The faucet is not working, everytime I try to get the tokens on Sepolia to claim my relay, it show this error: The contract function "fund" reverted with the following reason: Insufficient contract token balance.
I have more than 100 ANYONE tokens on mainnet.

**Comment by glaucoab** [comment]
Balance error on my wallet.

**Comment by Gordonhills** [comment]
Hello @glaucoab 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ANY07638
Please see the link below to our dedicated support line:
[Anyone protocol Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
